version: '3'
services:
  dmodel:
    image: davmonsch/dmodel
    ports:
      - '8090:8080'
    expose:
      - '8080'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8080'
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      pcm-docker: null
      condition: service_healthy
  pcm-docker:
    image: davmonsch/pcm-headless-rest
    expose:
      - '8080'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8080'
      interval: 30s
      timeout: 10s
      retries: 5
  registry:
    image: teastore-registry
    expose:
      - '8080'
  db:
    image: 'descartesresearch/teastore-db:1.3.3'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    depends_on:
      dmodel:
        condition: service_healthy
  persistence:
    image: teastore-persistence
    expose:
      - '8080'
    environment:
      HOST_NAME: persistence
      REGISTRY_HOST: registry
      DB_HOST: db
      DB_PORT: '3306'
    depends_on:
      dmodel:
        condition: service_healthy
  auth:
    image: teastore-auth
    expose:
      - '8080'
    environment:
      HOST_NAME: auth
      REGISTRY_HOST: registry
    depends_on:
      dmodel:
        condition: service_healthy
  image:
    image: teastore-image
    expose:
      - '8080'
    environment:
      HOST_NAME: image
      REGISTRY_HOST: registry
    depends_on:
      dmodel:
        condition: service_healthy
  recommender:
    image: teastore-recommender
    expose:
      - '8080'
    environment:
      HOST_NAME: recommender
      REGISTRY_HOST: registry
    depends_on:
      dmodel:
        condition: service_healthy
  webui:
    image: teastore-webui
    expose:
      - '8080'
    environment:
      HOST_NAME: webui
      REGISTRY_HOST: registry
depends_on:
  dmodel:
    condition: service_healthy
  ports:
    - '8080:8080'
